name: GitHub Classroom Workflow

on:
  push:
    paths:
      - 'assignment.py'
      - 'test_assignment.py'

permissions:
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests (FAIL if wrong)
        run: pytest -q --tb=no
